### PR TITLE
Sprint 2/issue 15#create profile client screen

### LINKED ISSUE #15: Create Profile Client Screen
## DESCRIPTION

Design and develop a Profile Form screen that allows users to input or update their personal information. The form should be intuitive and user-friendly, ensuring a seamless user experience.

## TASKS

- [x]  Design the layout for the Profile Form screen, including fields for user information such as name, email, profile picture, etc.
- [x]  Create the necessary graphical assets for the Profile Form screen, such as input fields, buttons, icons, etc.
- [x]  Implement the design into the application, ensuring the layout and visuals align with the overall application aesthetic.

### PR DESCRIPTION
**Pull request by Tole15**
# Development of ProfileClientScreen and its Reusable Components for Client and Service Provider

This pull request introduces the **ProfileClientScreen** along with several reusable components catering to both clients and service providers. The main components added are:

1. **ProfileClientSimpleCard** (`<ProfileClientSimpleCard />`):
   This reusable component provides a simple card layout specifically designed for client profiles. It presents essential client details in a visually appealing manner.

2. **ProfileClientForm** (`<ProfileClientForm />`):
   The **ProfileClientForm** component serves as a comprehensive and adaptable form that clients or providers can use to provide or update their information.

3. **InputField** (`<InputField />`):
   The **InputField** component is a versatile and reusable input element that can be utilized within various forms and screens. It allows users to enter different types of data, such as text, numbers, or selections, based on their specific requirements.

4. **Button** (`<Button />`):
   The **Button** component is a highly versatile and customizable button element that can be utilized throughout the application for various actions and interactions. It offers a consistent and visually appealing way for users to trigger actions like submitting forms, navigating between screens, or confirming selections.

By implementing these reusable components, the codebase becomes more modular and maintainable, as these elements can be flexibly reused throughout the application whenever similar functionalities are needed. This approach not only promotes consistency in the user interface but also enhances productivity for the oppenbarbies team when working on future features or updates. The pull request aims to improve the overall user experience and streamline the development process for both client and service provider interfaces.
screenshot_1691017839_720

### CODE REVIEW

**Review by DerekAyala — APPROVED** [review]
Nice Nice

**Review by Eduardoespl — COMMENTED** [review]
Great Work!

**Review by Eduardoespl — APPROVED** [review]

**Review by Antonio3veces3 — APPROVED** [review]
Excelente Trabaj, muy bien hecho tu codigo!

**Review by juperameza — APPROVED** [review]
There shouldn't be that many changes 🗣️
Someone already explained me what happened but you should put that in the pr description

**Pull request merged**
