### PR TITLE
Sprint 4/issue 54#create view available time component

### LINKED ISSUE #54: Create View Available Time component
## REQUIREMENTS / DESCRIPTION

> A new component should be created from the provider's available times and displayed in a flatlist

```[tasklist]
### Tasks
- [ ] Create the component
- [ ] Get the data from the array of the available time from Details - Provider
- [ ] Show the data in a flatlist
```

## DESIGN

image

### PR DESCRIPTION
**Pull request by Tole15**
ViewAvailableTime Component:

Purpose: This component is designed to render and show the available time slots for a given day or period. It integrates with the data source to fetch and display time slots, enabling users to see when they can book or schedule an event.
Directory Structure: The component is housed within the components directory for better organization.
Component Anatomy: The component uses a list view (or similar visual structure) to render each available time slot. Each slot is tappable/clickable for further actions like booking or viewing details.
Styling & Responsiveness:

Integrated with the previously established styles directory to maintain a consistent visual theme across the app.
The component is made responsive to cater to various screen sizes and orientations.
image

### CODE REVIEW

**Review by montsegv-2 — APPROVED** [review]
LGTM ⭐

**Review by Eduardoespl — APPROVED** [review]
LGTM!

**Review by DerekAyala — APPROVED** [review]

**Review by BrandonVG — APPROVED** [review]

**Review by AlbertoG22 — APPROVED** [review]
Excellent work!

**Pull request merged**
