### PR TITLE
Sprint 2/issue 16#create profile view screen

### LINKED ISSUE #16: Create Profile View Screen
## DESCRIPTION

Design and develop a Profile View screen that allows users to view their profile information. The screen should present the user's details in an organized and visually appealing manner.

## TASKS

- [x]  Design the layout for the Profile View screen, determining how to display user information such as name, profile picture, email, etc.
- [x]  Create the necessary graphical assets for the Profile View screen, such as profile picture frames, icons for user information, etc.
- [x] Implement the design into the application, ensuring the layout and visuals align with the overall application aesthetic.

### PR DESCRIPTION
**Pull request by Eduardoespl**
# Description

In this pull request, the following changes have been made:

- Created a new styles file for "HomeClientScreen.tsx" to manage the styles for the screen.
- Created a new navbar component with user icons, a calendar to view appointments, and a search icon to search for providers. Added this navbar component to "HomeClientScreen.tsx".
- Added the gear icon to "HomeClientScreen" to simulate a button for modifying user data.
- Created a new "Rating" component for the provider's rating.
- Created two new components to display client or provider information in "HomeClientScreen".

This pull request enhances the "HomeClientScreen" with several new features and components. The new navbar provides easy access to user-related actions and searching for providers. The gear icon simulates the ability to modify user data. The "Rating" component enables displaying the provider's rating effectively. The new information components enhance the user experience by displaying relevant client or provider information.

# Justification
These changes aim to improve the visual appeal and functionality of the "HomeClientScreen" for a better user experience. The new navbar and information components provide users with quick access to relevant actions and information. Additionally, the "Rating" component enriches the provider's profile by showcasing their rating. These enhancements contribute to a more engaging and user-friendly application.

## Screenshots

image image

### CODE REVIEW

**Review by Antonio3veces3 — APPROVED** [review]
Excelente trabajo!

**Review by Lizzflores — APPROVED** [review]
LGTM!

**Review by BrandonVG — APPROVED** [review]
LGBTQ+🏳️‍🌈

**Review by DerekAyala — APPROVED** [review]
Great job team

**Review by FebernalGober — APPROVED** [review]

**Pull request merged**
