### PR TITLE
Firebase Setup with React Native Config Integration

### LINKED ISSUE #11: Set Up Firebase Project
Description: Create a Firebase project and configure it for the application.
Tasks:
- [] Create a new Firebase project in the Firebase console.
- [] Configure the Firebase SDK in the application.
- [] Connect Proyect to app

### PR DESCRIPTION
**Pull request by DerekAyala**
# Description

This pull request adds Firebase to the project and configures it using React Native Config to securely manage sensitive Firebase keys.

# Changes made.

- Installed Firebase in the project.
- Integrated React Native Config to handle Firebase keys securely.
- Set up the .env file with the necessary Firebase keys using React Native Config.

## Screenshots
image

### CODE REVIEW

**Review by Tole15 — APPROVED** [review]

**Review by Tole15 — APPROVED** [review]

**Review by Ewar22 — APPROVED** [review]
Lgtm

**Review by Antonio3veces3 — APPROVED** [review]
Well done!

**Review by xFerchoVJ — APPROVED** [review]
LGTM!
Nice code!

**Review by BrandonVG — APPROVED** [review]
image

**Pull request merged**
