### PR TITLE
Sprint 3/issue 30#s create available days appoinment calendar

### LINKED ISSUE #30: Create calendar
## REQUIREMENTS / DESCRIPTION

You will create the calendar component where the client user can see the availables days about the service provider selected. With this information the client user knows what day thei can choose.

- [x] Create available days appoinment calendar component.

## DESIGN
The component should look like this:
The days disabled must be marks with red color.

SPcalendar

### PR DESCRIPTION
**Pull request by Tole15**
# Description

**Changes Made:**
This PR contains several changes that focus on enhancing and optimizing the appointment calendar in our application:

1. **CalendarModal Component and Dependencies (commit 5e43d01):** Added a new component called CalendarModal using react-native-modern-datepicker and date-fns for an improved date picking experience. Defined styles and updated colors.

2. **Type Fixes and Formatting (commit 0f58f9b):** Fixed type issues within the code and applied the prettier formatter to all files to maintain code consistency.

3. **Addition of declarations.d File (commit c270944):** Added a declarations file to ensure TypeScript functionality with the modern picker calendar and added eslint comments to bypass linting in config files.

4. **Name Corrections and Imports (commit a6186da):** Made corrections to some components' names, imports, and data to ensure optimal working.

**Overall Effect of the PR:**
The combination of these changes results in a significant enhancement in the functionality of the appointment calendar, offering a better user experience and fixing previous technical issues.

**Ticket Reference:**
This PR addresses issue #30 in our issue tracker, detailing the requirements for improving the appointment calendar system.

**Why It's Important:**
From a technical standpoint, these changes improve efficiency and code quality. From a business perspective, they enhance the user experience in scheduling appointments, a critical aspect of our application, thus satisfying a key business need.

## Screenshots
image

### CODE REVIEW

**Review by BrandonVG — APPROVED** [review]
Nice job, remember to remove the console.log lines that you have in your CalendarModal.tsx
Like gato

**Review by montsegv-2 — APPROVED** [review]
Good job 💯

**Review by Eduardoespl — APPROVED** [review]
LGTM

**Comment by Tole15** [comment]
> Nice job, remember to remove the console.log lines that you have in your CalendarModal.tsx
> Like gato
> 

They were left to test the functionality of the components and ensure that the data is saved in the correct format for when we fully implement the database, so that we can verify that the data is successfully being saved. Here's a descriptive image for reference:
# Image

**Pull request merged**
